### ISSUE TITLE
it will not take direction "left 

### ISSUE THREAD

**Issue by ahmad-fathy-1981** [RonnyWeiss/APEX-Floating-Button-Menu#1]
it toke same direction as right side whether the application RTL or LTR !
![RTL](https://user-images.githubusercontent.com/57535548/118347347-39b0e100-b54b-11eb-988b-dc7d23c186b1.jpg)
![LTR](https://user-images.githubusercontent.com/57535548/118347349-3c133b00-b54b-11eb-97f6-14f67301dc30.jpg)

**Comment by RonnyWeiss** [comment]
Hello You can set the position by json. So you can try to set calc(100vw - 149px) in json attribute btnPositionRight. Would that help?

**Comment by RonnyWeiss** [comment]
No reacton after weeks.... Will Close the Issues
